### ISSUE TITLE
大佬日志怎么看，运行了没有反应

### ISSUE THREAD

**Issue by yl948** [BarryLiu1995/bili-fav-sniffer#1]
启动页面了也填写相应的值了，没有反应不通知，怎么看日志，大佬们出个视频吗，这个只映射一个路径吗

**Comment by SummerLiu95** [comment]
拉取一下最新的镜像，昨天刚添加的日志功能
![](https://i.328888.xyz/2023/03/17/KTgBJ.png)

**Comment by SummerLiu95** [comment]
后面也会增加test按钮测试填写的值是否生效

**Comment by yl948** [comment]
好的大佬，我试一下

**Comment by yl948** [comment]
还是只显示这一行Listening on port 3000 url: http://2b8112b9f53b:3000不知道哪里没有搞对，路径映射就知道downloads吧

**Comment by yl948** [comment]
version: "3"
services:
  bili-fav-sniffer:
    image: fish95/bili-fav-sniffer:latest
    container_name: bili-fav-sniffer
    volumes:
      - /mnt/asus/bilibili/downloads:/usr/you-get-download
    restart: unless-stopped
    ports:
      - 3000:3000
    network_mode: bridge

这是我的compose

**Comment by yl948** [comment]
让一个玩nas的群友装了也是这样，不知道是不是姿势不对，这个貌似每次重新拉取就需要重新填配置，这个配置文件能否也映射一下

**Comment by SummerLiu95** [comment]
> 还是只显示这一行Listening on port 3000 url: [http://2b8112b9f53b:3000不知道哪里没有搞对，路径映射就知道downloads吧](http://2b8112b9f53b:3000%E4%B8%8D%E7%9F%A5%E9%81%93%E5%93%AA%E9%87%8C%E6%B2%A1%E6%9C%89%E6%90%9E%E5%AF%B9%EF%BC%8C%E8%B7%AF%E5%BE%84%E6%98%A0%E5%B0%84%E5%B0%B1%E7%9F%A5%E9%81%93downloads%E5%90%A7)

对一开始运行确实只显示一行，等后面下载开始执行的时候才会有相应的日志展示

**Comment by SummerLiu95** [comment]
> 让一个玩nas的群友装了也是这样，不知道是不是姿势不对，这个貌似每次重新拉取就需要重新填配置，这个配置文件能否也映射一下

姿势看着没错。对每次拉取镜像都要重新配置，之前其实是本地配置文件去运行的，后来觉得会不会很多人不会用，才写了个页面去生成配置文件，这个我记录一下后期增加本地文件配置映射的功能，免去每次拉取镜像都要重新配置的烦恼

**Comment by yl948** [comment]
是得，把数据配置到本地比较好，还是没有正常使用，啥都进去了就是填了运行后没有工作，
![IMG_20230317_212036](https://user-images.githubusercontent.com/70079656/226106180-baed7e9e-eae1-4f18-8304-8115e398f747.jpg)
我的是这样填的

**Comment by SummerLiu95** [comment]
> 是得，把数据配置到本地比较好，还是没有正常使用，啥都进去了就是填了运行后没有工作，
> ![IMG_20230317_212036](https://user-images.githubusercontent.com/70079656/226106180-baed7e9e-eae1-4f18-8304-8115e398f747.jpg)
> 我的是这样填的

日志有打印什么吗？

**Comment by yl948** [comment]
/
![Uploading IMG_20230319_230725.jpg…]()

**Comment by yl948** [comment]
![IMG_20230319_230725](https://user-images.githubusercontent.com/70079656/226185419-27fdfce8-13ba-48ed-ac38-797992886711.jpg)

**Comment by yl948** [comment]
就打印这个没了

**Comment by SummerLiu95** [comment]
OK，看着镜像运行是没问题，可能是下载的脚本执行有问题。看来可以增加手动单次运行的功能
