### ISSUE TITLE
cookies 已失效

### ISSUE THREAD

**Issue by hansky1211** [BarryLiu1995/bili-fav-sniffer#10]
使用在威联通x86nas docker软件中
bilibili账号已登录，配置已导入，自建rss源。

日志中显示：
‘’favorites title: 呦厚厚呦 的 bilibili 收藏夹 saveandbackup
cookies 已失效
script failed executed and exited
‘’

**Comment by SummerLiu95** [comment]
有尝试重新登陆嘛，看看重新登陆是否还会出现”cookies 已失效“这个问题

**Comment by hansky1211** [comment]
> 有尝试重新登陆嘛，看看重新登陆是否还会出现”cookies 已失效“这个问题
重新登陆多次仍出现问题。最后重新拉取镜像重新配置，不登陆也不会复现问题了
