### ISSUE TITLE
自定义tg api

### ISSUE THREAD

**Issue by koolcandy** [BarryLiu1995/bili-fav-sniffer#18]
你好,可以考虑添加自定义tg api的选项,要不然要进sniffer.sh改

**Comment by SummerLiu95** [comment]
你好，这个可能目前不太考虑去专门为 tg 的 api 增加选项，针对消息通知这块，后续想去实现多渠道消息推送功能

**Comment by koolcandy** [comment]
好的,感谢你的回复
