### ISSUE TITLE
docker部署运行还是不行

### ISSUE THREAD

**Issue by ljw98** [BarryLiu1995/bili-fav-sniffer#2]
docker部署成功，设置参数也没有问题（rss也可以打开），但是就是不能正常下载视频，请教是什么原因导致的
![image](https://user-images.githubusercontent.com/38665646/229289916-4649b0a2-d853-4c8a-bffa-c970167658a9.png)

**Comment by SummerLiu95** [comment]
这应该是网络不稳定造成的。我这边偶尔也会遇到这种情况，这种情况下下次任务运行的时候会自动重新尝试下载。你的设置参数应该没有问题
