### ISSUE TITLE
The process closed is not correct

### ISSUE THREAD

**Issue by zsnmwy** [BarryLiu1995/bili-fav-sniffer#4]
The process closed is not correct.

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/35299017/231970062-47525313-80b3-4be5-84d2-d1f7af4d688f.png">

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/35299017/231970981-b765ccc0-9e52-498a-a299-ba2904a597dc.png">

---
It seems to try to download the video again and again.

[video](https://www.bilibili.com/video/BV1Px4y1K77q)

**Comment by SummerLiu95** [comment]
Do you fill the favorite url? And I see the url you offer is the video url

**Comment by zsnmwy** [comment]
> Do you fill the favorite url? And I see the url you offer is the video url

Try this fav URL.

https://space.bilibili.com/845096/favlist?fid=2254159596

**Comment by SummerLiu95** [comment]
<img width="1172" alt="iShot_2023-04-21_14 29 05" src="https://user-images.githubusercontent.com/20590350/233558316-a51e71f4-0def-4910-83f0-2e3bc2db98b7.png">
<img width="1166" alt="iShot_2023-04-21_14 29 22" src="https://user-images.githubusercontent.com/20590350/233558328-5175b481-2116-4164-b877-607ee9fa2364.png">

I used the URL you provided attempt and found no problem with the process exception using latest image

**Comment by SummerLiu95** [comment]
and you can use latest image to try again
