### ISSUE TITLE
无法下载私密收藏夹，只能改成公共收藏夹再下载

### ISSUE THREAD

**Issue by zwxhugh** [BarryLiu1995/bili-fav-sniffer#6]
下载的时候只能把私密收藏夹设置成公开才能下载，下载速度并不快，需要长时间公开。
看了下大神的计划，应该都有涉及，加油，感谢，很好用。

**Comment by SummerLiu95** [comment]
是的哈，因为受制于 rsshub。后续计划替换掉 rsshub

**Comment by zwxhugh** [comment]
好的，昨天试了下一个比较大的收藏夹，结果中途下载自己停了。还是有点不稳定，一旦收藏夹视频多了，很容易中断不下了；收藏夹中包含失效视频也会中断；收藏的视频为系列视频（收藏夹中显示为一个视频，实际是一个系列课程）也会中断。

**Comment by zwxhugh** [comment]
只能下收藏夹的第一页么，怎么只下载了第一页就告诉我完成了 = =。script execution process exited with code 0

**Comment by SummerLiu95** [comment]
> 只能下收藏夹的第一页么，怎么只下载了第一页就告诉我完成了 = =。script execution process exited with code 0

是的，也是因为 rsshub 只会抓取收藏夹第一页的信息，后面替换掉 rsshub 会解决这个问题

**Comment by SummerLiu95** [comment]
> 好的，昨天试了下一个比较大的收藏夹，结果中途下载自己停了。还是有点不稳定，一旦收藏夹视频多了，很容易中断不下了；收藏夹中包含失效视频也会中断；收藏的视频为系列视频（收藏夹中显示为一个视频，实际是一个系列课程）也会中断。

失效视频跳过这块我记录一下，后续解决掉。因为目前下载都是一个进程上按照顺序依次下载，然后可能又会收到网络波动的影响，导致如果视频太多的话一下子全部下载下来容易因为各种问题导致整个流程中断。我这边测试的时候也发现了同个视频有时候下载快有时候下载慢，这块我再排查一下。感谢你的反馈！

**Comment by zwxhugh** [comment]
大神可以再测一下20个以上的视频收藏夹的下载，包含一两百的视频收藏夹测试下下载最好了，它会显示“script execution process exited with code 0”其实暂时中断也没事，只要可以重启继续。都是慢慢优化的，但是主要功能影响就太致命了。加油！

**Comment by SummerLiu95** [comment]
> 大神可以再测一下20个以上的视频收藏夹的下载，包含一两百的视频收藏夹测试下下载最好了，它会显示“script execution process exited with code 0”其实暂时中断也没事，只要可以重启继续。都是慢慢优化的，但是主要功能影响就太致命了。加油！

RssHub 只会抓取一个收藏夹的第一个分页，刚好就是 20 个视频，所以只会下载最近收藏的前 20 个视频（合集）。关于显示 script execution process exited with code 0，它其实就是表示一次 shell 脚本的执行完成后正常退出

**Comment by SummerLiu95** [comment]
> 大神可以再测一下20个以上的视频收藏夹的下载，包含一两百的视频收藏夹测试下下载最好了，它会显示“script execution process exited with code 0”其实暂时中断也没事，只要可以重启继续。都是慢慢优化的，但是主要功能影响就太致命了。加油！

之前没有测试过有包含一两百个视频的视频合集的下载，只测试过包含五十个视频的视频合集的下载，可以给个一两百个视频的视频合集地址吗？我有时间试试

**Comment by zwxhugh** [comment]
汗，你这么告诉我，那我那个只下载20个视频的就是因为rsshub的原因了。那说明视频多了其实不影响，还是rsshub的原因，视频中包含系列视频应该也是这个原因。我还一直以为是中断来着，原来是视频数量超了。

**Comment by SummerLiu95** [comment]
> 汗，你这么告诉我，那我那个只下载20个视频的就是因为rsshub的原因了。那说明视频多了其实不影响，还是rsshub的原因，视频中包含系列视频应该也是这个原因。我还一直以为是中断来着，原来是视频数量超了。

哈哈哈对的
