### ISSUE TITLE
下载只有封面，没有视频

### ISSUE THREAD

**Issue by ContinueStudio** [BarryLiu1995/bili-fav-sniffer#7]
我在b站看到有人跟我一样的情况，是我们哪里没设置好吗？

**Comment by SummerLiu95** [comment]
有具体的运行日志吗？可以贴一下

**Comment by kaiklife** [comment]
date | stream | content
-- | -- | --
2023/05/30 07:31:38 | stdout | script execution process exited with code 0
2023/05/30 07:31:38 | stdout | ValueError: not enough values to unpack (expected 7, got 1)
2023/05/30 07:31:38 | stdout | domain, domain_specified, path, secure, expires, name, value = \
2023/05/30 07:31:38 | stdout | File "/usr/lib/python3.10/site-packages/you_get/common.py", line 1411, in load_cookies
2023/05/30 07:31:38 | stdout | load_cookies(args.cookies)
2023/05/30 07:31:38 | stdout | File "/usr/lib/python3.10/site-packages/you_get/common.py", line 1711, in script_main
2023/05/30 07:31:38 | stdout | script_main(any_download, any_download_playlist, **kwargs)
2023/05/30 07:31:38 | stdout | File "/usr/lib/python3.10/site-packages/you_get/common.py", line 1870, in main
2023/05/30 07:31:38 | stdout | main(**kwargs)
2023/05/30 07:31:38 | stdout | File "/usr/lib/python3.10/site-packages/you_get/__main__.py", line 92, in main
2023/05/30 07:31:38 | stdout | sys.exit(main())
2023/05/30 07:31:38 | stdout | File "/usr/bin/you-get", line 8, in <module>
2023/05/30 07:31:38 | stdout | Traceback (most recent call last):
2023/05/30 07:31:38 | stdout | '/usr/you-get-download/【保姆教程】2T只要23元？iCloud最佳使用方案，零门槛，手把手教会国区合理使用土耳其区\|土区苹果iCloud \| 宝藏大叔/【保姆教程】2T只要23元？iCloud最佳使用方案，零门槛，手把手教会国区合理使用土耳其区\|土区苹果iCloud \| 宝藏大叔.jpg' saved
2023/05/30 07:31:38 | stdout | 【保姆教程】2T只要23 100% \|********************************\|  130k  0:00:00 ETA
2023/05/30 07:31:38 | stdout | saving to '/usr/you-get-download/【保姆教程】2T只要23元？iCloud最佳使用方案，零门槛，手把手教会国区合理使用土耳其区\|土区苹果iCloud \| 宝藏大叔/【保姆教程】2T只要23元？iCloud最佳使用方案，零门槛，手把手教会国区合理使用土耳其区\|土区苹果iCloud \| 宝藏大叔.jpg'
2023/05/30 07:31:38 | stdout | Connecting to i1.hdslb.com (121.17.124.104:80)
2023/05/30 07:31:38 | stdout | poster link: http://i1.hdslb.com/bfs/archive/b0168a9e33b9bbcc8171e24bf2edcaa8a09fca86.jpg
2023/05/30 07:31:37 | stdout | video title: 【保姆教程】2T只要23元？iCloud最佳使用方案，零门槛，手把手教会国区合理使用土耳其区\|土区苹果iCloud \| 宝藏大叔
2023/05/30 07:31:37 | stdout | ValueError: not enough values to unpack (expected 7, got 1)
2023/05/30 07:31:37 | stdout | domain, domain_specified, path, secure, expires, name, value = \
2023/05/30 07:31:37 | stdout | File "/usr/lib/python3.10/site-packages/you_get/common.py", line 1411, in load_cookies
2023/05/30 07:31:37 | stdout | load_cookies(args.cookies)
2023/05/30 07:31:37 | stdout | File "/usr/lib/python3.10/site-packages/you_get/common.py", line 1711, in script_main
2023/05/30 07:31:37 | stdout | script_main(any_download, any_download_playlist, **kwargs)
2023/05/30 07:31:37 | stdout | File "/usr/lib/python3.10/site-packages/you_get/common.py", line 1870, in main
2023/05/30 07:31:37 | stdout | main(**kwargs)
2023/05/30 07:31:37 | stdout | File "/usr/lib/python3.10/site-packages/you_get/__main__.py", line 92, in main
2023/05/30 07:31:37 | stdout | sys.exit(main())
2023/05/30 07:31:37 | stdout | File "/usr/bin/you-get", line 8, in <module>
2023/05/30 07:31:37 | stdout | Traceback (most recent call last):
2023/05/30 07:31:37 | stdout | favorites title: 伏狸不是虎 的 bilibili 收藏夹 知识
2023/05/30 07:26:47 | stdout | Listening on port [33m3000[39m url: http://fish95-bili-fav-sniffer-1:3000

**Comment by kaiklife** [comment]
> 有具体的运行日志吗？可以贴一下



date | stream | content
-- | -- | --
2023/05/30 07:31:38 | stdout | script execution process exited with code 0
2023/05/30 07:31:38 | stdout | ValueError: not enough values to unpack (expected 7, got 1)
2023/05/30 07:31:38 | stdout | domain, domain_specified, path, secure, expires, name, value = \
2023/05/30 07:31:38 | stdout | File "/usr/lib/python3.10/site-packages/you_get/common.py", line 1411, in load_cookies
2023/05/30 07:31:38 | stdout | load_cookies(args.cookies)
2023/05/30 07:31:38 | stdout | File "/usr/lib/python3.10/site-packages/you_get/common.py", line 1711, in script_main
2023/05/30 07:31:38 | stdout | script_main(any_download, any_download_playlist, **kwargs)
2023/05/30 07:31:38 | stdout | File "/usr/lib/python3.10/site-packages/you_get/common.py", line 1870, in main
2023/05/30 07:31:38 | stdout | main(**kwargs)
2023/05/30 07:31:38 | stdout | File "/usr/lib/python3.10/site-packages/you_get/__main__.py", line 92, in main
2023/05/30 07:31:38 | stdout | sys.exit(main())
2023/05/30 07:31:38 | stdout | File "/usr/bin/you-get", line 8, in <module>
2023/05/30 07:31:38 | stdout | Traceback (most recent call last):
2023/05/30 07:31:38 | stdout | '/usr/you-get-download/【保姆教程】2T只要23元？iCloud最佳使用方案，零门槛，手把手教会国区合理使用土耳其区\|土区苹果iCloud \| 宝藏大叔/【保姆教程】2T只要23元？iCloud最佳使用方案，零门槛，手把手教会国区合理使用土耳其区\|土区苹果iCloud \| 宝藏大叔.jpg' saved
2023/05/30 07:31:38 | stdout | 【保姆教程】2T只要23 100% \|********************************\|  130k  0:00:00 ETA
2023/05/30 07:31:38 | stdout | saving to '/usr/you-get-download/【保姆教程】2T只要23元？iCloud最佳使用方案，零门槛，手把手教会国区合理使用土耳其区\|土区苹果iCloud \| 宝藏大叔/【保姆教程】2T只要23元？iCloud最佳使用方案，零门槛，手把手教会国区合理使用土耳其区\|土区苹果iCloud \| 宝藏大叔.jpg'
2023/05/30 07:31:38 | stdout | Connecting to i1.hdslb.com (121.17.124.104:80)
2023/05/30 07:31:38 | stdout | poster link: http://i1.hdslb.com/bfs/archive/b0168a9e33b9bbcc8171e24bf2edcaa8a09fca86.jpg
2023/05/30 07:31:37 | stdout | video title: 【保姆教程】2T只要23元？iCloud最佳使用方案，零门槛，手把手教会国区合理使用土耳其区\|土区苹果iCloud \| 宝藏大叔
2023/05/30 07:31:37 | stdout | ValueError: not enough values to unpack (expected 7, got 1)
2023/05/30 07:31:37 | stdout | domain, domain_specified, path, secure, expires, name, value = \
2023/05/30 07:31:37 | stdout | File "/usr/lib/python3.10/site-packages/you_get/common.py", line 1411, in load_cookies
2023/05/30 07:31:37 | stdout | load_cookies(args.cookies)
2023/05/30 07:31:37 | stdout | File "/usr/lib/python3.10/site-packages/you_get/common.py", line 1711, in script_main
2023/05/30 07:31:37 | stdout | script_main(any_download, any_download_playlist, **kwargs)
2023/05/30 07:31:37 | stdout | File "/usr/lib/python3.10/site-packages/you_get/common.py", line 1870, in main
2023/05/30 07:31:37 | stdout | main(**kwargs)
2023/05/30 07:31:37 | stdout | File "/usr/lib/python3.10/site-packages/you_get/__main__.py", line 92, in main
2023/05/30 07:31:37 | stdout | sys.exit(main())
2023/05/30 07:31:37 | stdout | File "/usr/bin/you-get", line 8, in <module>
2023/05/30 07:31:37 | stdout | Traceback (most recent call last):
2023/05/30 07:31:37 | stdout | favorites title: 伏狸不是虎 的 bilibili 收藏夹 知识
2023/05/30 07:26:47 | stdout | Listening on port [33m3000[39m url: http://fish95-bili-fav-sniffer-1:3000

**Comment by SummerLiu95** [comment]
可以参考一下 you-get 的这个 [issue](https://github.com/soimort/you-get/pull/2838)
