### ISSUE TITLE
Cookie 检测失效

### ISSUE THREAD

**Issue by Fengyee** [BarryLiu1995/bili-fav-sniffer#9]
群晖 Container Manager 2023/07/27 安装后无法通过Cookie检测

Log 中有 bilix 报错，检查发现 bilix 不是最新版本 0.18.4，手动更新 `pip install --upgrade bilix`，我看 DockerFile 没有看出是为什么

还是无法通过检测，发现是登录后需要有大会员才会有 4K 视频的 codec，修改 `sniffer.sh` 检测 `1080P` instead of `4K`，我认为这是一个 Bug

BTW, 我想知道为什么限制下载速度等：`bilix s "$link" --subtitle --dm --image -nh --debug -d "$folderName" -vc 1 -sl 2MB -sr 2 -pc 2  --cookie "$sessdata_value"`

**Comment by SummerLiu95** [comment]
你好，请问有具体的日志截图嘛。我目前在群晖 7.1 的 docker 中运行是正常的，没有试过在 7.2 的 container manager 运行。
至于为什么限制下载速度，第一个是考虑这个下载服务避免占用太多的带宽影响其他上网行为。第二个是如果大量下载任务不限速进行下载有可能会触发bilibili的安全机制，所以限速是为了减少触发安全机制的可能

**Comment by Fengyee** [comment]
> 至于为什么限制下载速度，第一个是考虑这个下载服务避免占用太多的带宽影响其他上网行为。第二个是如果大量下载任务不限速进行下载有可能会触发bilibili的安全机制，所以限速是为了减少触发安全机制的可能

明白了

我的系统是 DSM 7.2-64570 Update 1，日志文件在这里：
[fish95-bili-fav-sniffer-1.csv](https://github.com/BarryLiu1995/bili-fav-sniffer/files/12234675/fish95-bili-fav-sniffer-1.csv)

我的解决方法就是自己手动 update 一下 bilix，然后改一下 sniffer.sh

**Comment by SummerLiu95** [comment]
> > 至于为什么限制下载速度，第一个是考虑这个下载服务避免占用太多的带宽影响其他上网行为。第二个是如果大量下载任务不限速进行下载有可能会触发bilibili的安全机制，所以限速是为了减少触发安全机制的可能
> 
> 明白了
> 
> 我的系统是 DSM 7.2-64570 Update 1，日志文件在这里： [fish95-bili-fav-sniffer-1.csv](https://github.com/BarryLiu1995/bili-fav-sniffer/files/12234675/fish95-bili-fav-sniffer-1.csv)
> 
> 我的解决方法就是自己手动 update 一下 bilix，然后改一下 sniffer.sh

看了一下日志文件，感觉是 bilix 这个下载器内部解析视频信息的有错误抛出，不知道是不是兼容性问题。你的解决办法最后有效吗？

**Comment by Fengyee** [comment]
有效的

**Comment by SummerLiu95** [comment]
> 有效的

好的，那应该只要让 bilix 保持最新版本就可以。有意愿的话可以提个 pr 😂

**Comment by Fengyee** [comment]
哈哈 但是找不出具体是什么愿意也没啥好commit的，如果有人遇到相似的问题就看issue叭
